#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'runit'
cookbook 'ohai'
cookbook 'git'
cookbook 'openssl'
#cookbook 'locales', :git => "https://github.com/optiflows-cookbooks/locales", :ref => "generate_current_locale"
cookbook 'locale', '~> 1.0.2'
cookbook 'postgresql'
cookbook 'redis'
cookbook 'rvm'
cookbook 'logrotate', '~> 1.9.1'
cookbook 'sendmail', '~> 0.1.0'
cookbook 'memcached', '~> 1.7.2'
cookbook 'ufw'
